### ISSUE TITLE
regex not found

### ISSUE THREAD

**Issue by ktpi2000** [Massu0921/FreeDLHelper#31]
READMEにある`pip3 install regex` が正しく実行できません。

regex https://bitbucket.org/mrabarnett/mrab-regex/src/default/

![image](https://user-images.githubusercontent.com/30472855/84167663-7bbae280-aab1-11ea-91cb-5655478d3bbd.png)

**Comment by Massu0921** [comment]
リンク切れ修正，現時点でregexがインストールできることを確認しました
